import Foundation

// Research-only parser. It is deliberately outside MealMirror.swiftpm until
// representative, consented exports from both vendors have been validated.
enum HistoricalCSVSource: String, Equatable {
    case dexcomClarity
    case libreView
}

enum HistoricalGlucoseUnit: String, Equatable {
    case milligramsPerDeciliter = "mg/dL"
    case millimolesPerLiter = "mmol/L"
}

struct HistoricalCSVReading: Equatable {
    let source: HistoricalCSVSource
    // Exported device-local wall time. No timezone is present in either
    // examined CSV example, so this is intentionally not a Date.
    let localTimestamp: String
    let value: Decimal
    let unit: HistoricalGlucoseUnit
}

struct HistoricalCSVImport: Equatable {
    let source: HistoricalCSVSource
    let readings: [HistoricalCSVReading]
    let ignoredNonGlucoseRows: Int
    let ignoredCensoredReadings: Int
}

enum HistoricalCSVImportError: Error, Equatable {
    case fileTooLarge
    case invalidEncoding
    case malformedCSV
    case unsupportedFormat
    case providerExportUnsupported
    case missingOrDuplicateColumns
    case malformedRow
    case malformedTimestamp
    case invalidGlucose
    case noReadings
}

enum HistoricalCSVPrototype {
    static let maximumBytes = 25 * 1024 * 1024

    static func parse(_ data: Data) throws -> HistoricalCSVImport {
        guard data.count <= maximumBytes else { throw HistoricalCSVImportError.fileTooLarge }
        guard var text = String(data: data, encoding: .utf8) else {
            throw HistoricalCSVImportError.invalidEncoding
        }
        if text.hasPrefix("\u{FEFF}") { text.removeFirst() }
        let rows = try parseCSV(text)
        guard let first = rows.first, let marker = first.first else {
            throw HistoricalCSVImportError.unsupportedFormat
        }

        if marker == "Patient report" {
            throw HistoricalCSVImportError.providerExportUnsupported
        }
        if marker == "Glucose Data" {
            return try parseLibreView(rows)
        }
        if marker == "Index" {
            return try parseDexcomClarity(rows)
        }
        throw HistoricalCSVImportError.unsupportedFormat
    }

    private static func parseDexcomClarity(_ rows: [[String]]) throws -> HistoricalCSVImport {
        let header = try indices(rows[0], requiring: [
            "Index", "Timestamp (YYYY-MM-DDThh:mm:ss)", "Event Type", "Glucose Value (mg/dL)"
        ])
        var readings: [HistoricalCSVReading] = []
        var ignored = 0
        var censored = 0
        for row in rows.dropFirst() {
            guard row.count == rows[0].count else { throw HistoricalCSVImportError.malformedRow }
            guard row[header["Event Type"]!] == "EGV" else {
                ignored += 1
                continue
            }
            let timestamp = row[header["Timestamp (YYYY-MM-DDThh:mm:ss)"]!]
            guard validDexcomTimestamp(timestamp) else {
                throw HistoricalCSVImportError.malformedTimestamp
            }
            let rawValue = row[header["Glucose Value (mg/dL)"]!]
            if rawValue == "High" || rawValue == "Low" {
                censored += 1
                continue
            }
            let value = try glucose(rawValue)
            readings.append(.init(source: .dexcomClarity,
                                  localTimestamp: timestamp,
                                  value: value,
                                  unit: .milligramsPerDeciliter))
        }
        guard !readings.isEmpty else { throw HistoricalCSVImportError.noReadings }
        return .init(source: .dexcomClarity, readings: readings,
                     ignoredNonGlucoseRows: ignored, ignoredCensoredReadings: censored)
    }

    private static func parseLibreView(_ rows: [[String]]) throws -> HistoricalCSVImport {
        guard rows.count >= 2, rows[0].count >= 4,
              rows[0][1] == "Generated on", rows[0][3] == "Generated by" else {
            throw HistoricalCSVImportError.unsupportedFormat
        }
        let header = try indices(rows[1], requiring: ["Device", "Device Timestamp", "Record Type"])
        let mg = header["Historic Glucose mg/dL"]
        let mmol = header["Historic Glucose mmol/L"]
        guard (mg == nil) != (mmol == nil) else {
            throw HistoricalCSVImportError.missingOrDuplicateColumns
        }
        let valueColumn = mg ?? mmol!
        let unit: HistoricalGlucoseUnit = mg == nil ? .millimolesPerLiter : .milligramsPerDeciliter
        var readings: [HistoricalCSVReading] = []
        var ignored = 0
        for row in rows.dropFirst(2) {
            guard row.count == rows[1].count else { throw HistoricalCSVImportError.malformedRow }
            // Type 0 is the historical series in the examined export. Scan,
            // strip, meal and insulin records must not be counted as CGM points.
            guard row[header["Record Type"]!] == "0" else {
                ignored += 1
                continue
            }
            let timestamp = row[header["Device Timestamp"]!]
            guard validLibreTimestamp(timestamp) else {
                throw HistoricalCSVImportError.malformedTimestamp
            }
            let value = try glucose(row[valueColumn])
            readings.append(.init(source: .libreView,
                                  localTimestamp: timestamp,
                                  value: value,
                                  unit: unit))
        }
        guard !readings.isEmpty else { throw HistoricalCSVImportError.noReadings }
        return .init(source: .libreView, readings: readings,
                     ignoredNonGlucoseRows: ignored, ignoredCensoredReadings: 0)
    }

    private static func indices(_ fields: [String], requiring required: [String]) throws -> [String: Int] {
        var index: [String: Int] = [:]
        for (offset, field) in fields.enumerated() {
            guard index[field] == nil else { throw HistoricalCSVImportError.missingOrDuplicateColumns }
            index[field] = offset
        }
        guard required.allSatisfy({ index[$0] != nil }) else {
            throw HistoricalCSVImportError.missingOrDuplicateColumns
        }
        return index
    }

    private static func glucose(_ raw: String) throws -> Decimal {
        guard raw.range(of: #"^[0-9]+(?:\.[0-9]+)?$"#, options: .regularExpression) != nil,
              let value = Decimal(string: raw, locale: Locale(identifier: "en_US_POSIX")),
              value > 0, value < 10_000 else {
            throw HistoricalCSVImportError.invalidGlucose
        }
        return value
    }

    private static func validDexcomTimestamp(_ text: String) -> Bool {
        guard text.range(of: #"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$"#, options: .regularExpression) != nil else {
            return false
        }
        let parts = text.split(whereSeparator: { $0 == "-" || $0 == "T" || $0 == ":" }).compactMap { Int($0) }
        return parts.count == 6 && validDate(year: parts[0], month: parts[1], day: parts[2]) &&
            validClock(hour: parts[3], minute: parts[4], second: parts[5])
    }

    private static func validLibreTimestamp(_ text: String) -> Bool {
        guard text.range(of: #"^\d{1,2}[-/]\d{1,2}[-/]\d{4} \d{1,2}:\d{2}(?::\d{2})?$"#, options: .regularExpression) != nil else {
            return false
        }
        let halves = text.split(separator: " ")
        guard halves.count == 2 else { return false }
        guard !(halves[0].contains("/") && halves[0].contains("-")) else { return false }
        let date = halves[0].split(whereSeparator: { $0 == "-" || $0 == "/" }).compactMap { Int($0) }
        let clock = halves[1].split(separator: ":").compactMap { Int($0) }
        guard date.count == 3, clock.count == 2 || clock.count == 3 else { return false }
        // The two observed LibreView date layouts use opposite day/month order.
        // Validate either order, but keep the original text because the locale
        // cannot be inferred from an ambiguous date such as 4/12/2023.
        return (validDate(year: date[2], month: date[0], day: date[1]) ||
                validDate(year: date[2], month: date[1], day: date[0])) &&
            validClock(hour: clock[0], minute: clock[1], second: clock.count == 3 ? clock[2] : 0)
    }

    private static func validDate(year: Int, month: Int, day: Int) -> Bool {
        guard (1...9999).contains(year), (1...12).contains(month) else { return false }
        let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)
        let days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
        return (1...days[month - 1]).contains(day)
    }

    private static func validClock(hour: Int, minute: Int, second: Int) -> Bool {
        (0...23).contains(hour) && (0...59).contains(minute) && (0...59).contains(second)
    }

    private static func parseCSV(_ text: String) throws -> [[String]] {
        enum State { case start, plain, quoted, afterQuote }
        let bytes = Array(text.utf8)
        var rows: [[String]] = []
        var row: [String] = []
        var field: [UInt8] = []
        var state = State.start
        var index = 0

        func endField() {
            row.append(String(decoding: field, as: UTF8.self))
            field.removeAll(keepingCapacity: true)
        }
        func endRow() {
            endField()
            rows.append(row)
            row.removeAll(keepingCapacity: true)
        }

        while index < bytes.count {
            let byte = bytes[index]
            if state == .quoted {
                if byte == 34 { state = .afterQuote } else { field.append(byte) }
                index += 1
                continue
            }
            if state == .afterQuote {
                if byte == 34 { field.append(34); state = .quoted; index += 1; continue }
                guard byte == 44 || byte == 10 || byte == 13 else {
                    throw HistoricalCSVImportError.malformedCSV
                }
            } else if byte == 34 {
                guard state == .start else { throw HistoricalCSVImportError.malformedCSV }
                state = .quoted
                index += 1
                continue
            }
            if byte == 44 {
                endField()
                state = .start
            } else if byte == 10 || byte == 13 {
                endRow()
                state = .start
                if byte == 13, index + 1 < bytes.count, bytes[index + 1] == 10 { index += 1 }
            } else {
                field.append(byte)
                state = .plain
            }
            index += 1
        }
        guard state != .quoted else { throw HistoricalCSVImportError.malformedCSV }
        if state != .start || !row.isEmpty || !field.isEmpty { endRow() }
        return rows
    }
}
