import Foundation

@main
struct ImportProbe {
    static let dexcomHeader = [
        "Index", "Timestamp (YYYY-MM-DDThh:mm:ss)", "Event Type", "Event Subtype",
        "Patient Info", "Device Info", "Source Device ID", "Glucose Value (mg/dL)",
        "Insulin Value (u)", "Carb Value (grams)", "Duration (hh:mm:ss)",
        "Glucose Rate of Change (mg/dL/min)", "Transmitter Time (Long Integer)", "Transmitter ID"
    ]
    static let libreHeader = [
        "Device", "Serial Number", "Device Timestamp", "Record Type",
        "Historic Glucose mg/dL", "Scan Glucose mg/dL", "Non-numeric Rapid-Acting Insulin",
        "Rapid-Acting Insulin (units)", "Non-numeric Food", "Carbohydrates (grams)",
        "Carbohydrates (servings)", "Non-numeric Long-Acting Insulin",
        "Long-Acting Insulin (units)", "Notes", "Strip Glucose mg/dL",
        "Ketone mmol/L", "Meal Insulin (units)", "Correction Insulin (units)",
        "User Change Insulin (units)"
    ]

    static func line(_ values: [Int: String], width: Int) -> String {
        var fields = Array(repeating: "", count: width)
        for (index, value) in values { fields[index] = value }
        return fields.joined(separator: ",")
    }

    static func parse(_ csv: String) throws -> HistoricalCSVImport {
        try HistoricalCSVPrototype.parse(Data(csv.utf8))
    }

    static func expect(_ error: HistoricalCSVImportError, _ csv: String) {
        do {
            _ = try parse(csv)
            fatalError("Expected \(error)")
        } catch let actual as HistoricalCSVImportError {
            precondition(actual == error, "Expected \(error), got \(actual)")
        } catch {
            fatalError("Unexpected error: \(error)")
        }
    }

    static func main() throws {
        let dexcom = ([dexcomHeader.joined(separator: ","),
                       line([0: "1", 2: "FirstName", 3: "Synthetic"], width: 14),
                       line([0: "2", 1: "2026-01-15T12:00:00", 2: "EGV", 7: "110"], width: 14),
                       line([0: "3", 1: "2026-01-15T12:05:00", 2: "EGV", 7: "High"], width: 14),
                       line([0: "4", 1: "2026-01-15T12:10:00", 2: "Carbs", 9: "30"], width: 14),
                       line([0: "5", 1: "2026-01-15T12:15:00", 2: "EGV", 7: "123"], width: 14)]
            .joined(separator: "\r\n") + "\r\n")
        let d = try parse(dexcom)
        precondition(d.source == .dexcomClarity && d.readings.count == 2)
        precondition(d.ignoredNonGlucoseRows == 2 && d.ignoredCensoredReadings == 1)
        precondition(d.readings[0].localTimestamp == "2026-01-15T12:00:00")
        precondition(d.readings[0].value == 110 && d.readings[0].unit == .milligramsPerDeciliter)

        let libreMetadata = "Glucose Data,Generated on,2026-01-16 12:00 UTC,Generated by,\"Synthetic, Example\""
        let libre = ([libreMetadata, libreHeader.joined(separator: ","),
                      line([0: "FreeStyle Libre 3", 2: "4/12/2023 14:30", 3: "0", 4: "130"], width: 19),
                      line([0: "FreeStyle Libre 3", 2: "4/12/2023 14:35", 3: "1", 5: "131"], width: 19)]
            .joined(separator: "\n") + "\n")
        let l = try parse(libre)
        precondition(l.source == .libreView && l.readings.count == 1)
        precondition(l.ignoredNonGlucoseRows == 1 && l.ignoredCensoredReadings == 0)
        precondition(l.readings[0].localTimestamp == "4/12/2023 14:30")
        precondition(l.readings[0].value == 130)

        var mmolHeader = libreHeader
        mmolHeader[4] = "Historic Glucose mmol/L"
        mmolHeader[5] = "Scan Glucose mmol/L"
        let mmol = ([libreMetadata, mmolHeader.joined(separator: ","),
                     line([0: "FreeStyle Libre 3", 2: "12-04-2023 14:30", 3: "0", 4: "7.2"], width: 19)]
            .joined(separator: "\n"))
        let m = try parse(mmol)
        precondition(m.readings[0].unit == .millimolesPerLiter && m.readings[0].value == Decimal(string: "7.2")!)

        expect(.providerExportUnsupported, "Patient report,Generated on,2026-01-16,Generated by,Clinician\n")
        expect(.unsupportedFormat, "time,glucose\n2026-01-15,110\n")
        expect(.missingOrDuplicateColumns,
               "Glucose Data,Generated on,2026-01-16,Generated by,Example\n" +
               libreHeader.map { $0 == "Historic Glucose mg/dL" ? "Historic Glucose" : $0 }.joined(separator: ","))
        expect(.malformedCSV, "Index,\"unclosed\n")
        expect(.malformedRow, dexcomHeader.joined(separator: ",") + "\n1,2026-01-15T12:00:00,EGV,110\n")
        expect(.invalidGlucose, dexcomHeader.joined(separator: ",") + "\n" +
               line([0: "1", 1: "2026-01-15T12:00:00", 2: "EGV", 7: "NaN"], width: 14))
        expect(.malformedTimestamp, dexcomHeader.joined(separator: ",") + "\n" +
               line([0: "1", 1: "01/15/2026 12:00", 2: "EGV", 7: "110"], width: 14))
        expect(.malformedTimestamp, dexcomHeader.joined(separator: ",") + "\n" +
               line([0: "1", 1: "2026-02-30T12:00:00", 2: "EGV", 7: "110"], width: 14))
        expect(.malformedTimestamp, libreMetadata + "\n" + libreHeader.joined(separator: ",") + "\n" +
               line([0: "FreeStyle Libre 3", 2: "31/31/2023 14:30", 3: "0", 4: "130"], width: 19))
        let bom = try parse("\u{FEFF}" + dexcom)
        precondition(bom == d)
        let multilineMetadata = try parse(libre.replacingOccurrences(of: "Synthetic, Example", with: "Synthetic\nExample"))
        precondition(multilineMetadata == l)
        expect(.missingOrDuplicateColumns,
               dexcomHeader.map { $0 == "Glucose Value (mg/dL)" ? "Event Type" : $0 }.joined(separator: ","))
        expect(.malformedTimestamp, libreMetadata + "\n" + libreHeader.joined(separator: ",") + "\n" +
               line([0: "FreeStyle Libre 3", 2: "4/12-2023 14:30", 3: "0", 4: "130"], width: 19))
        print("16 synthetic CSV import checks passed")
    }
}
